[project]
name = "iris-mlops-ci-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dvc-gs>=3.0.2",
    "joblib>=1.5.2",
    "mlflow>=3.6.0",
    "pandas>=2.3.3",
    "pytest>=9.0.1",
    "scikit-learn>=1.7.2",
]
