name: MLOps CD Pipeline

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev] # Temporarily keep PRs to dev for testing

env:
  PROJECT_ID: buoyant-country-473106-a3
  GAR_LOCATION: us-central1-docker.pkg.dev
  GAR_REPO: iris-repo
  IMAGE_NAME: iris-api
  GKE_CLUSTER: iris-cluster
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: iris-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin'
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for GAR
        run: gcloud auth configure-docker $GAR_LOCATION

      - name: Build Docker image
        run: |
          docker build -t $GAR_LOCATION/$PROJECT_ID/$GAR_REPO/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image to Google Artifact Registry
        run: |
          docker push $GAR_LOCATION/$PROJECT_ID/$GAR_REPO/$IMAGE_NAME:${{ github.sha }}

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$GAR_LOCATION/$PROJECT_ID/$GAR_REPO/$IMAGE_NAME:${{ github.sha }} --record
          kubectl rollout status deployment/$DEPLOYMENT_NAME